name: Force delete unauthorized writer's issue
on:
  issues:
    types: [opened]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - if: github.event.issue.user.login != github.repository_owner
        name: Delete Issue
        run: gh issue delete $NUMBER --yes
        env:
          #GH_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ secrets.ISSUE_CLOSE_TOKEN }} # admin role for delet
          GH_REPO:  ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
        #uses: peter-evans/close-issue@v3.0.1
        #with:
        #  close-reason: not_planned
        #  comment: only the owner can post. 
