name: Force close unauthorized writer's issue
on:
  issues:
    types: [opened]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - if: github.event.issue.user.login != github.repository_owner
        name: Close Issue
        uses: peter-evans/close-issue@v3.0.1
        with:
          close-reason: not_planned
          comment: only the owner can post. 
