name: Close utterances issue
on:
  issues:
    types: [opened]
jobs:
  close-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - if: github.event.issue.user.login != 'lepffm'
        name: Close Issue
        uses: peter-evans/close-issue@v3.0.1
        with:
          repository: lepffm/issuance
